# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c17543e079724ffb0bf2e7027ffe34e2c5c9d003d4324a4a4b44825b017196fd2dfa7b6e3cb04ff85779fa986b179a78850c438072614e220fa665c44b278426

test:
  secret_key_base: 4a36b11a107617346752929f864a91c35117be0f2cd71f69d6587b10a6ce309cb3055aaf2ad9d5c7230d843d7c2c34193570a308ba5ce32e08f1d17dc8ce2acc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
